# This workflow will check if the run.py files in every demo match the run.ipynb notebooks.

name: Check Demos Match Notebooks

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    paths:
        - 'demo/**'

jobs:
  check-notebooks:
    name: Generate Notebooks and Check 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Generate Notebooks
        run: |
          pip install nbformat && cd demo && python generate_notebooks.py
      - name: Print Git Status
        run: echo $(git status)
      - name: Assert Notebooks Match 
        run: git status | grep "nothing to commit, working tree clean"

