# This workflow will check if the run.py files in every demo match the run.ipynb notebooks.

name: Check Demos Match Notebooks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
        - 'demo/**'

jobs:
  check-notebooks:
    name: Generate Notebooks and Check 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Generate Notebooks
        run: |
          pip install nbformat && cd demo && python generate_notebooks.py
      - name: Print Git Status
        run: echo $(git status) && echo $(git diff)
      - name: Assert Notebooks Match 
        id: assertNotebooksMatch
        run: git status | grep "nothing to commit, working tree clean"
  - name: Comment On PR
      uses: thollander/actions-comment-pull-request@v1
      if: always() && (steps.assertNotebooksMatch.outcome == 'failure')
      with:
        message: |
          The demo notebooks don't match the run.py files. Please run this command from the root of the repo and then commit the changes:
          ```bash
          pip install nbformat && cd demo && python generate_notebooks.py
          ```
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}