name: "deploy website"

on:
  workflow_call:
    inputs:
      vercel_token:
        description: "Vercel API token"
        type: string
      branch_name:
        description: "The branch name"
        type: string
      github_token:
        description: "Github token"
        default: ${{ github.token }}
        type: string
      pr_number:
        description: "The PR number"
        type: number

jobs:
  deploy:
    name: "Deploy website"
    runs-on: ubuntu-latest
    steps:
      - name: comment pr (start)
        uses: "./.github/workflows/comment-queue.yml"
        with:
          token: ${{ inputs.github_token }}
          pr_number: ${{ inputs.pr_number }}
          message: "<website>:<pending>:<null>" 
      - name: Install Vercel CLI
        shell: bash
        run: pnpm install --global vercel@latest
      # preview
      - name: Pull Vercel Environment Information
        shell: bash
        if: github.event_name == 'pull_request'
        run: vercel pull --yes --environment=preview --token=${{ inputs.vercel_token }}
      - name: Build Project Artifacts
        if: github.event_name == 'pull_request'
        shell: bash
        run: vercel build --token=${{ inputs.vercel_token }}
      - name: Deploy Project Artifacts to Vercel
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "VERCEL_URL=$(vercel deploy --prebuilt --token=${{ inputs.vercel_token }})" >> $GITHUB_ENV
      # production
      - name: Pull Vercel Environment Information
        if: github.event_name == 'push' && inputs.branch_name == 'main'
        shell: bash
        run: vercel pull --yes --environment=production --token=${{ inputs.vercel_token }}
      - name: Build Project Artifacts
        if: github.event_name == 'push' && inputs.branch_name == 'main'
        shell: bash
        run: vercel build --prod --token=${{ inputs.vercel_token }}
      - name: Deploy Project Artifacts to Vercel
        if: github.event_name == 'push' && inputs.branch_name == 'main'
        shell: bash
        run: echo "deploying production"
        # run: echo "VERCEL_URL=$(vercel deploy --prebuilt --prod --token=${{ inputs.vercel_token }})" >> $GITHUB_ENV
      - name: echo vercel url
        shell: bash
        run: echo $VERCEL_URL #add to comment
      - name: comment pr (end)
        uses: "./.github/workflows/comment-queue.yml"
        with:
          token: ${{ inputs.github_token }}
          pr_number: ${{ github.event.pull_request.number }}
          message: "<website>:<sucess>:<$VERCEL_URL>" 
