name: "hygiene"

on:
  pull_request:
  push:
    branches:
      - main
      - 5.0-dev

concurrency:
  group: "${{ github.event.pull_request.number }}-${{ github.ref_name }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Notebooks
        run: |
          pip install nbformat && python scripts/generate_notebooks.py
      - name: Print Git Status
        run: echo $(git status) && echo $(git diff)
      - name: Assert Notebooks Match
        run: git status | grep "nothing to commit, working tree clean"
      - name: Check for large files
        uses: actionsdesk/lfs-warning@v3.3
        with:
          filesizelimit: 5MB
