name: trigger changeset generation
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
    branches:
      - main
      - v4
  issue_comment:
    types: [edited]

jobs:
  version:
    permissions: write-all
    name: static checks
    runs-on: ubuntu-22.04
    if: github.event.sender.login != 'gradio-pr-bot'
    steps:
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.event.sender.login }}
      - run: echo "Triggering changeset generation"
