name: gradio-ui

on:
  push:
    branches:
      - "main"
  pull_request:

defaults:
  run:
    working-directory: ui

env:
  CI: true
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
  NODE_OPTIONS: "--max-old-space-size=4096"

concurrency:
  group: deploy-${{ github.ref }}-${{ github.event_name == 'push' || github.event.inputs.fire != null }}
  cancel-in-progress: true

jobs:
  quick-checks:
    name: static checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
          cache-dependency-path: ui/pnpm-lock.yaml
      - name: install dependencies
        run: pnpm i --frozen-lockfile
      - name: formatting check
        run: pnpm format:check
      - name: typecheck
        run: pnpm ts:check
      - name: unit tests
        run: pnpm test:run
  functional-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
          cache-dependency-path: ui/pnpm-lock.yaml
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - run: python -m pip install --upgrade pip
      - run: cd .. && bash scripts/install_gradio.sh
      - run: pip install -r ../demo/outbreak_forecast/requirements.txt
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec playwright install chromium
      - run: pnpm test:browser:full
      - name: Upload failed tests screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          retention-days: 3
          name: test-failure-${{ github.run_id }}
          path: ui/packages/app/test-results
